# This is a basic workflow to help you get started with Actions

name: publish message to slack channel

# Controls when the workflow will run
on:
  # Triggers the workflow by other workflows
  workflow_call:
    secrets:
      slack_webhook:
        required: true
    inputs:
  
  # Manually trigger the workflow
  workflow_dispatch:
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  slack_notification:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Slack Notificatio
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.slack_webhook }}
          SLACK_MESSAGE: 'Hello Slack :rocket:'
